//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dogovorIznajmuvanje
    {
        public int idDogovorIznajmuvanje { get; set; }
        public System.DateTime dataOd { get; set; }
        public System.DateTime dataDo { get; set; }
        public int idDogovor { get; set; }
    
        public virtual dogovor dogovor { get; set; }
    }
}
