//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgencijaZaNEdvizniniEntities : DbContext
    {
        public AgencijaZaNEdvizniniEntities()
            : base("name=AgencijaZaNEdvizniniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dogovor> dogovors { get; set; }
        public DbSet<dogovorIznajmuvanje> dogovorIznajmuvanjes { get; set; }
        public DbSet<dogovorProdavanje> dogovorProdavanjes { get; set; }
        public DbSet<kancelarija> kancelarijas { get; set; }
        public DbSet<klient> klients { get; set; }
        public DbSet<kukja> kukjas { get; set; }
        public DbSet<objekt> objekts { get; set; }
        public DbSet<sopstvenik> sopstveniks { get; set; }
        public DbSet<stan> stans { get; set; }
        public DbSet<Tip_Korisnik> Tip_Korisnik { get; set; }
        public DbSet<tip_na_dogovor> tip_na_dogovor { get; set; }
        public DbSet<vraboten> vrabotens { get; set; }
    }
}
